version: "3.9"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGREST_USER: postgres
      POSTGREST_PASSWORD: 123
      POSTGRES_DB: nest
  test-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest